# Form implementation generated from reading ui file '.\ui\uiFiles\adminMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AdminMain(object):
    def setupUi(self, AdminMain):
        AdminMain.setObjectName("AdminMain")
        AdminMain.resize(1000, 750)
        AdminMain.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(AdminMain)
        self.verticalLayout_2.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.table = QtWidgets.QTableWidget(parent=AdminMain)
        self.table.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.table.setStyleSheet("QHeaderView::section { \n"
"    background-color: #252A34; \n"
"    color: white;\n"
"    font: 57 13pt \"Roboto Mono Medium\";\n"
"}\n"
"\n"
"QTableWidget {\n"
"    border: None;\n"
"}")
        self.table.setShowGrid(True)
        self.table.setGridStyle(QtCore.Qt.PenStyle.SolidLine)
        self.table.setWordWrap(True)
        self.table.setCornerButtonEnabled(True)
        self.table.setRowCount(10)
        self.table.setObjectName("table")
        self.table.setColumnCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(6, item)
        self.table.horizontalHeader().setVisible(True)
        self.table.horizontalHeader().setHighlightSections(True)
        self.table.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.table)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.searchBtn = QtWidgets.QPushButton(parent=AdminMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchBtn.sizePolicy().hasHeightForWidth())
        self.searchBtn.setSizePolicy(sizePolicy)
        self.searchBtn.setMinimumSize(QtCore.QSize(120, 0))
        self.searchBtn.setMaximumSize(QtCore.QSize(120, 16777215))
        self.searchBtn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 46, 99);\n"
"    color : white;\n"
"    border-radius: 4px;\n"
"    font: 57 11pt \"Roboto Mono Medium\";\n"
"}")
        self.searchBtn.setObjectName("searchBtn")
        self.horizontalLayout_2.addWidget(self.searchBtn)
        self.searchTf = QtWidgets.QLineEdit(parent=AdminMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchTf.sizePolicy().hasHeightForWidth())
        self.searchTf.setSizePolicy(sizePolicy)
        self.searchTf.setMinimumSize(QtCore.QSize(350, 40))
        self.searchTf.setMaximumSize(QtCore.QSize(400, 40))
        self.searchTf.setStyleSheet("QLineEdit {\n"
"    padding-left : 10px;\n"
"    border: None;\n"
"    border-radius : 5px;\n"
"    background-color: rgba(32, 64, 48, 180);\n"
"    color : white;\n"
"}\n"
"\n"
"")
        self.searchTf.setObjectName("searchTf")
        self.horizontalLayout_2.addWidget(self.searchTf)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.enableEditingBox = QtWidgets.QCheckBox(parent=AdminMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.enableEditingBox.sizePolicy().hasHeightForWidth())
        self.enableEditingBox.setSizePolicy(sizePolicy)
        self.enableEditingBox.setObjectName("enableEditingBox")
        self.horizontalLayout.addWidget(self.enableEditingBox)
        self.carBox = QtWidgets.QCheckBox(parent=AdminMain)
        self.carBox.setObjectName("carBox")
        self.horizontalLayout.addWidget(self.carBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(AdminMain)
        QtCore.QMetaObject.connectSlotsByName(AdminMain)

    def retranslateUi(self, AdminMain):
        _translate = QtCore.QCoreApplication.translate
        AdminMain.setWindowTitle(_translate("AdminMain", "Form"))
        self.table.setSortingEnabled(False)
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("AdminMain", "Car"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("AdminMain", "Model"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("AdminMain", "Year"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("AdminMain", "Gear"))
        item = self.table.horizontalHeaderItem(4)
        item.setText(_translate("AdminMain", "Gas"))
        item = self.table.horizontalHeaderItem(5)
        item.setText(_translate("AdminMain", "Price"))
        self.searchBtn.setText(_translate("AdminMain", "Search"))
        self.enableEditingBox.setText(_translate("AdminMain", "Editing"))
        self.carBox.setText(_translate("AdminMain", "Show Car"))
