# Form implementation generated from reading ui file 'ui\uiFiles\appointmentsWindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6.QtWidgets import QHBoxLayout, QPushButton


class Ui_appointments:
    active_appointments_layout: QHBoxLayout
    inactive_appointments_layout: QHBoxLayout
    back_btn: QPushButton