# Form implementation generated from reading ui file 'ui\uiFiles\appointmentsWindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_appointments(object):
    def setupUi(self, appointments):
        appointments.setObjectName("appointments")
        appointments.resize(1001, 750)
        self.verticalLayout = QtWidgets.QVBoxLayout(appointments)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_app_bar = QtWidgets.QWidget(parent=appointments)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.top_app_bar.sizePolicy().hasHeightForWidth())
        self.top_app_bar.setSizePolicy(sizePolicy)
        self.top_app_bar.setMinimumSize(QtCore.QSize(0, 100))
        self.top_app_bar.setMaximumSize(QtCore.QSize(16777215, 100))
        self.top_app_bar.setStyleSheet("background-color: rgb(27, 71, 229);\n"
"color: #F0F0F0;")
        self.top_app_bar.setObjectName("top_app_bar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.top_app_bar)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.appointments_label = QtWidgets.QLabel(parent=self.top_app_bar)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(24)
        self.appointments_label.setFont(font)
        self.appointments_label.setObjectName("appointments_label")
        self.horizontalLayout_2.addWidget(self.appointments_label)
        self.verticalLayout.addWidget(self.top_app_bar)
        self.active_groupbox = QtWidgets.QGroupBox(parent=appointments)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono Medium")
        font.setPointSize(10)
        self.active_groupbox.setFont(font)
        self.active_groupbox.setObjectName("active_groupbox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.active_groupbox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.active_groupbox)
        self.scrollArea.setStyleSheet("border: None;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.active_appointments_widget = QtWidgets.QWidget()
        self.active_appointments_widget.setGeometry(QtCore.QRect(0, 0, 977, 271))
        self.active_appointments_widget.setObjectName("active_appointments_widget")
        self.scrollArea.setWidget(self.active_appointments_widget)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.verticalLayout.addWidget(self.active_groupbox)
        self.inactive_groupbox = QtWidgets.QGroupBox(parent=appointments)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono Medium")
        font.setPointSize(10)
        self.inactive_groupbox.setFont(font)
        self.inactive_groupbox.setObjectName("inactive_groupbox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.inactive_groupbox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea_2 = QtWidgets.QScrollArea(parent=self.inactive_groupbox)
        self.scrollArea_2.setStyleSheet("border:None;")
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.inactive_appointments_widget = QtWidgets.QWidget()
        self.inactive_appointments_widget.setGeometry(QtCore.QRect(0, 0, 977, 271))
        self.inactive_appointments_widget.setObjectName("inactive_appointments_widget")
        self.scrollArea_2.setWidget(self.inactive_appointments_widget)
        self.verticalLayout_3.addWidget(self.scrollArea_2)
        self.verticalLayout.addWidget(self.inactive_groupbox)

        self.retranslateUi(appointments)
        QtCore.QMetaObject.connectSlotsByName(appointments)

    def retranslateUi(self, appointments):
        _translate = QtCore.QCoreApplication.translate
        appointments.setWindowTitle(_translate("appointments", "Form"))
        self.appointments_label.setText(_translate("appointments", "Appointments"))
        self.active_groupbox.setTitle(_translate("appointments", "Active"))
        self.inactive_groupbox.setTitle(_translate("appointments", "Inactive"))
