# Form implementation generated from reading ui file '.\uiFiles\carSelectionWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CarWidget(object):
    def setupUi(self, CarWidget):
        CarWidget.setObjectName("CarWidget")
        CarWidget.resize(1000, 801)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CarWidget.sizePolicy().hasHeightForWidth())
        CarWidget.setSizePolicy(sizePolicy)
        CarWidget.setStyleSheet("#carWidget {\n"
"    background-color: #EAEAEA;\n"
"}\n"
"\n"
"#filterWidget {\n"
"    background-color: rgb(37, 47, 52);\n"
"}\n"
"\n"
"#titleWidget {\n"
"    background-color: #252A34;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(CarWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleWidget = QtWidgets.QWidget(parent=CarWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleWidget.sizePolicy().hasHeightForWidth())
        self.titleWidget.setSizePolicy(sizePolicy)
        self.titleWidget.setMinimumSize(QtCore.QSize(1000, 100))
        self.titleWidget.setMaximumSize(QtCore.QSize(16777215, 100))
        self.titleWidget.setObjectName("titleWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.titleWidget)
        self.horizontalLayout_4.setContentsMargins(20, -1, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.slogan = QtWidgets.QLabel(parent=self.titleWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slogan.sizePolicy().hasHeightForWidth())
        self.slogan.setSizePolicy(sizePolicy)
        self.slogan.setMinimumSize(QtCore.QSize(458, 78))
        self.slogan.setStyleSheet("")
        self.slogan.setText("")
        self.slogan.setPixmap(QtGui.QPixmap(".\\uiFiles\\../assets/Drive_Freedom_Rent_Easy.png"))
        self.slogan.setScaledContents(False)
        self.slogan.setObjectName("slogan")
        self.horizontalLayout_4.addWidget(self.slogan)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(-1, 12, 17, 12)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.nameLabel = QtWidgets.QLabel(parent=self.titleWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono Medium")
        font.setPointSize(15)
        self.nameLabel.setFont(font)
        self.nameLabel.setStyleSheet("color: white;")
        self.nameLabel.setObjectName("nameLabel")
        self.verticalLayout_8.addWidget(self.nameLabel, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.prevligedLabel = QtWidgets.QLabel(parent=self.titleWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono Light")
        font.setPointSize(10)
        self.prevligedLabel.setFont(font)
        self.prevligedLabel.setStyleSheet("color: white;")
        self.prevligedLabel.setObjectName("prevligedLabel")
        self.verticalLayout_8.addWidget(self.prevligedLabel, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        self.profileIcon = QtWidgets.QLabel(parent=self.titleWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profileIcon.sizePolicy().hasHeightForWidth())
        self.profileIcon.setSizePolicy(sizePolicy)
        self.profileIcon.setMinimumSize(QtCore.QSize(48, 0))
        self.profileIcon.setMaximumSize(QtCore.QSize(48, 16777215))
        self.profileIcon.setStyleSheet("")
        self.profileIcon.setText("")
        self.profileIcon.setPixmap(QtGui.QPixmap(".\\uiFiles\\../assets/icons/profile_1.png"))
        self.profileIcon.setObjectName("profileIcon")
        self.horizontalLayout_4.addWidget(self.profileIcon)
        self.verticalLayout.addWidget(self.titleWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.filterWidget = QtWidgets.QWidget(parent=CarWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterWidget.sizePolicy().hasHeightForWidth())
        self.filterWidget.setSizePolicy(sizePolicy)
        self.filterWidget.setMinimumSize(QtCore.QSize(300, 0))
        self.filterWidget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.filterWidget.setStyleSheet("")
        self.filterWidget.setObjectName("filterWidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.filterWidget)
        self.verticalLayout_7.setContentsMargins(-1, 10, -1, 0)
        self.verticalLayout_7.setSpacing(20)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.priceFilterWidget = QtWidgets.QWidget(parent=self.filterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.priceFilterWidget.sizePolicy().hasHeightForWidth())
        self.priceFilterWidget.setSizePolicy(sizePolicy)
        self.priceFilterWidget.setMinimumSize(QtCore.QSize(0, 100))
        self.priceFilterWidget.setMaximumSize(QtCore.QSize(16777215, 120))
        self.priceFilterWidget.setStyleSheet("QLineEdit {\n"
"    border-radius : 4px;\n"
"    border: None;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: white;\n"
"}\n"
"\n"
" #priceFilterWidget {\n"
"    border-bottom: 1px solid white;\n"
"}\n"
"\n"
"")
        self.priceFilterWidget.setObjectName("priceFilterWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.priceFilterWidget)
        self.verticalLayout_4.setContentsMargins(10, 10, 0, 10)
        self.verticalLayout_4.setSpacing(12)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.priceLabel = QtWidgets.QLabel(parent=self.priceFilterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.priceLabel.sizePolicy().hasHeightForWidth())
        self.priceLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono Medium")
        font.setPointSize(18)
        self.priceLabel.setFont(font)
        self.priceLabel.setStyleSheet("")
        self.priceLabel.setObjectName("priceLabel")
        self.verticalLayout_4.addWidget(self.priceLabel)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(15)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.maxPriceTextF = QtWidgets.QLineEdit(parent=self.priceFilterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxPriceTextF.sizePolicy().hasHeightForWidth())
        self.maxPriceTextF.setSizePolicy(sizePolicy)
        self.maxPriceTextF.setMinimumSize(QtCore.QSize(50, 35))
        self.maxPriceTextF.setMaximumSize(QtCore.QSize(50, 35))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(9)
        self.maxPriceTextF.setFont(font)
        self.maxPriceTextF.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.maxPriceTextF.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.maxPriceTextF.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.maxPriceTextF.setText("")
        self.maxPriceTextF.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.maxPriceTextF.setObjectName("maxPriceTextF")
        self.horizontalLayout_3.addWidget(self.maxPriceTextF)
        self.minPriceTextF = QtWidgets.QLineEdit(parent=self.priceFilterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minPriceTextF.sizePolicy().hasHeightForWidth())
        self.minPriceTextF.setSizePolicy(sizePolicy)
        self.minPriceTextF.setMinimumSize(QtCore.QSize(50, 35))
        self.minPriceTextF.setMaximumSize(QtCore.QSize(50, 35))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(9)
        self.minPriceTextF.setFont(font)
        self.minPriceTextF.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.minPriceTextF.setText("")
        self.minPriceTextF.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.minPriceTextF.setObjectName("minPriceTextF")
        self.horizontalLayout_3.addWidget(self.minPriceTextF)
        spacerItem = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_7.addWidget(self.priceFilterWidget)
        self.yearFilterWidget = QtWidgets.QWidget(parent=self.filterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yearFilterWidget.sizePolicy().hasHeightForWidth())
        self.yearFilterWidget.setSizePolicy(sizePolicy)
        self.yearFilterWidget.setMinimumSize(QtCore.QSize(0, 100))
        self.yearFilterWidget.setMaximumSize(QtCore.QSize(16777215, 120))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.yearFilterWidget.setFont(font)
        self.yearFilterWidget.setStyleSheet("QLineEdit {\n"
"    border-radius : 4px;\n"
"    border: None;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: white;\n"
"}\n"
"\n"
" #yearFilterWidget {\n"
"    border-bottom: 1px solid white;\n"
"}\n"
"\n"
"")
        self.yearFilterWidget.setObjectName("yearFilterWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.yearFilterWidget)
        self.verticalLayout_3.setContentsMargins(10, 0, 0, 10)
        self.verticalLayout_3.setSpacing(12)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.yearLabel = QtWidgets.QLabel(parent=self.yearFilterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yearLabel.sizePolicy().hasHeightForWidth())
        self.yearLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono Medium")
        font.setPointSize(18)
        self.yearLabel.setFont(font)
        self.yearLabel.setObjectName("yearLabel")
        self.verticalLayout_3.addWidget(self.yearLabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(15)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.maxYearTextF = QtWidgets.QLineEdit(parent=self.yearFilterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxYearTextF.sizePolicy().hasHeightForWidth())
        self.maxYearTextF.setSizePolicy(sizePolicy)
        self.maxYearTextF.setMinimumSize(QtCore.QSize(50, 35))
        self.maxYearTextF.setMaximumSize(QtCore.QSize(50, 35))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(9)
        self.maxYearTextF.setFont(font)
        self.maxYearTextF.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.maxYearTextF.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.maxYearTextF.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.maxYearTextF.setText("")
        self.maxYearTextF.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.maxYearTextF.setObjectName("maxYearTextF")
        self.horizontalLayout_2.addWidget(self.maxYearTextF)
        self.minYearTextF = QtWidgets.QLineEdit(parent=self.yearFilterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minYearTextF.sizePolicy().hasHeightForWidth())
        self.minYearTextF.setSizePolicy(sizePolicy)
        self.minYearTextF.setMinimumSize(QtCore.QSize(50, 35))
        self.minYearTextF.setMaximumSize(QtCore.QSize(50, 35))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(9)
        self.minYearTextF.setFont(font)
        self.minYearTextF.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.minYearTextF.setText("")
        self.minYearTextF.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.minYearTextF.setObjectName("minYearTextF")
        self.horizontalLayout_2.addWidget(self.minYearTextF)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_7.addWidget(self.yearFilterWidget)
        self.gearTypeWidget = QtWidgets.QWidget(parent=self.filterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gearTypeWidget.sizePolicy().hasHeightForWidth())
        self.gearTypeWidget.setSizePolicy(sizePolicy)
        self.gearTypeWidget.setMinimumSize(QtCore.QSize(0, 100))
        self.gearTypeWidget.setMaximumSize(QtCore.QSize(16777215, 120))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.gearTypeWidget.setFont(font)
        self.gearTypeWidget.setStyleSheet("QWidget {\n"
"    color : white;\n"
"}\n"
"\n"
"QCheckBox::indicator { /* Kutu kısmını temsil eder */\n"
"    border: none;  /* Kenarlığı kaldır */\n"
"    background-color: white;  /* İç rengi beyaz yap */\n"
"    border-radius : 3px;\n"
"}\n"
"\n"
"#gearTypeWidget {\n"
"    border-bottom: 1px solid white;\n"
"}")
        self.gearTypeWidget.setObjectName("gearTypeWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.gearTypeWidget)
        self.verticalLayout_5.setContentsMargins(10, 0, 0, 10)
        self.verticalLayout_5.setSpacing(12)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gearTypeLabel = QtWidgets.QLabel(parent=self.gearTypeWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gearTypeLabel.sizePolicy().hasHeightForWidth())
        self.gearTypeLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono Medium")
        font.setPointSize(18)
        self.gearTypeLabel.setFont(font)
        self.gearTypeLabel.setObjectName("gearTypeLabel")
        self.verticalLayout_5.addWidget(self.gearTypeLabel, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.manual = QtWidgets.QCheckBox(parent=self.gearTypeWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono Light")
        font.setPointSize(10)
        self.manual.setFont(font)
        self.manual.setObjectName("manual")
        self.verticalLayout_5.addWidget(self.manual, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.automatic = QtWidgets.QCheckBox(parent=self.gearTypeWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono Light")
        font.setPointSize(10)
        self.automatic.setFont(font)
        self.automatic.setObjectName("automatic")
        self.verticalLayout_5.addWidget(self.automatic, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.verticalLayout_7.addWidget(self.gearTypeWidget)
        self.fuelTypeWidget = QtWidgets.QWidget(parent=self.filterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fuelTypeWidget.sizePolicy().hasHeightForWidth())
        self.fuelTypeWidget.setSizePolicy(sizePolicy)
        self.fuelTypeWidget.setMinimumSize(QtCore.QSize(0, 100))
        self.fuelTypeWidget.setMaximumSize(QtCore.QSize(16777215, 120))
        self.fuelTypeWidget.setBaseSize(QtCore.QSize(0, 0))
        self.fuelTypeWidget.setStyleSheet("QWidget {\n"
"    color : white;\n"
"}\n"
"\n"
"QCheckBox::indicator { /* Kutu kısmını temsil eder */\n"
"    border: none;  /* Kenarlığı kaldır */\n"
"    background-color: white;  /* İç rengi beyaz yap */\n"
"    border-radius : 3px;\n"
"}\n"
"\n"
"#fuelTypeWidget {\n"
"    border-bottom: 1px solid white;\n"
"}")
        self.fuelTypeWidget.setObjectName("fuelTypeWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.fuelTypeWidget)
        self.verticalLayout_6.setContentsMargins(10, 0, 0, 10)
        self.verticalLayout_6.setSpacing(12)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.fuelTypeLabel = QtWidgets.QLabel(parent=self.fuelTypeWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fuelTypeLabel.sizePolicy().hasHeightForWidth())
        self.fuelTypeLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono Medium")
        font.setPointSize(18)
        self.fuelTypeLabel.setFont(font)
        self.fuelTypeLabel.setObjectName("fuelTypeLabel")
        self.verticalLayout_6.addWidget(self.fuelTypeLabel)
        self.diesel = QtWidgets.QCheckBox(parent=self.fuelTypeWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono Light")
        font.setPointSize(10)
        self.diesel.setFont(font)
        self.diesel.setStyleSheet("")
        self.diesel.setObjectName("diesel")
        self.verticalLayout_6.addWidget(self.diesel)
        self.gasoline = QtWidgets.QCheckBox(parent=self.fuelTypeWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono Light")
        font.setPointSize(10)
        self.gasoline.setFont(font)
        self.gasoline.setObjectName("gasoline")
        self.verticalLayout_6.addWidget(self.gasoline)
        self.verticalLayout_7.addWidget(self.fuelTypeWidget)
        self.searchTextF = QtWidgets.QLineEdit(parent=self.filterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchTextF.sizePolicy().hasHeightForWidth())
        self.searchTextF.setSizePolicy(sizePolicy)
        self.searchTextF.setMinimumSize(QtCore.QSize(0, 50))
        self.searchTextF.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono Medium")
        font.setPointSize(11)
        self.searchTextF.setFont(font)
        self.searchTextF.setStyleSheet("QLineEdit {\n"
"    padding-left : 10px;\n"
"    border: None;\n"
"    border-radius : 5px;\n"
"    background-color: rgba(32, 64, 48, 180);\n"
"    color : white;\n"
"}\n"
"\n"
"")
        self.searchTextF.setClearButtonEnabled(False)
        self.searchTextF.setObjectName("searchTextF")
        self.verticalLayout_7.addWidget(self.searchTextF)
        self.applyBtn = QtWidgets.QPushButton(parent=self.filterWidget)
        self.applyBtn.setMinimumSize(QtCore.QSize(0, 43))
        self.applyBtn.setMaximumSize(QtCore.QSize(16777215, 43))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono Medium")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.applyBtn.setFont(font)
        self.applyBtn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 46, 99);\n"
"    color : white;\n"
"    border-radius: 4px;\n"
"    font: 57 11pt \"Roboto Mono Medium\";\n"
"}")
        self.applyBtn.setObjectName("applyBtn")
        self.verticalLayout_7.addWidget(self.applyBtn)
        spacerItem2 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_7.addItem(spacerItem2)
        self.horizontalLayout.addWidget(self.filterWidget)
        self.scrollArea = QtWidgets.QScrollArea(parent=CarWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.scrollArea.setFont(font)
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.carWidget = QtWidgets.QWidget()
        self.carWidget.setGeometry(QtCore.QRect(0, 0, 696, 697))
        self.carWidget.setStyleSheet("#carWidget {\n"
"    background-color: #EAEAEA;\n"
"}\n"
"")
        self.carWidget.setObjectName("carWidget")
        self.carWidgetLayout = QtWidgets.QHBoxLayout(self.carWidget)
        self.carWidgetLayout.setContentsMargins(0, 0, 0, 0)
        self.carWidgetLayout.setSpacing(0)
        self.carWidgetLayout.setObjectName("carWidgetLayout")
        self.bottomSpacerLayout = QtWidgets.QVBoxLayout()
        self.bottomSpacerLayout.setSpacing(0)
        self.bottomSpacerLayout.setObjectName("bottomSpacerLayout")
        self.carWidgetLayout.addLayout(self.bottomSpacerLayout)
        self.scrollArea.setWidget(self.carWidget)
        self.horizontalLayout.addWidget(self.scrollArea)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(CarWidget)
        QtCore.QMetaObject.connectSlotsByName(CarWidget)

    def retranslateUi(self, CarWidget):
        _translate = QtCore.QCoreApplication.translate
        CarWidget.setWindowTitle(_translate("CarWidget", "Form"))
        self.nameLabel.setText(_translate("CarWidget", "John Doe"))
        self.prevligedLabel.setText(_translate("CarWidget", "User"))
        self.priceLabel.setText(_translate("CarWidget", "Price"))
        self.maxPriceTextF.setPlaceholderText(_translate("CarWidget", "min"))
        self.minPriceTextF.setPlaceholderText(_translate("CarWidget", "max"))
        self.yearLabel.setText(_translate("CarWidget", "Year"))
        self.maxYearTextF.setPlaceholderText(_translate("CarWidget", "min"))
        self.minYearTextF.setPlaceholderText(_translate("CarWidget", "max"))
        self.gearTypeLabel.setText(_translate("CarWidget", "Gear"))
        self.manual.setText(_translate("CarWidget", "Manual"))
        self.automatic.setText(_translate("CarWidget", "Automatic"))
        self.fuelTypeLabel.setText(_translate("CarWidget", "Fuel Types"))
        self.diesel.setText(_translate("CarWidget", "Diesel"))
        self.gasoline.setText(_translate("CarWidget", "Gasoline"))
        self.searchTextF.setPlaceholderText(_translate("CarWidget", "Search"))
        self.applyBtn.setText(_translate("CarWidget", "Apply"))
