# Form implementation generated from reading ui file '.\ui\uiFiles\carSelectionWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_car_selection(object):
    def setupUi(self, car_selection):
        car_selection.setObjectName("car_selection")
        car_selection.resize(1071, 801)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(car_selection.sizePolicy().hasHeightForWidth())
        car_selection.setSizePolicy(sizePolicy)
        car_selection.setStyleSheet("#carWidget {\n"
"    background-color: #EAEAEA;\n"
"}\n"
"\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(car_selection)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleWidget = QtWidgets.QWidget(parent=car_selection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleWidget.sizePolicy().hasHeightForWidth())
        self.titleWidget.setSizePolicy(sizePolicy)
        self.titleWidget.setMinimumSize(QtCore.QSize(1000, 100))
        self.titleWidget.setMaximumSize(QtCore.QSize(16777215, 100))
        self.titleWidget.setStyleSheet("#titleWidget {\n"
"    background-color: #1B47E5;\n"
"}")
        self.titleWidget.setObjectName("titleWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.titleWidget)
        self.horizontalLayout_4.setContentsMargins(20, -1, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.slogan = QtWidgets.QLabel(parent=self.titleWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slogan.sizePolicy().hasHeightForWidth())
        self.slogan.setSizePolicy(sizePolicy)
        self.slogan.setMinimumSize(QtCore.QSize(458, 78))
        self.slogan.setStyleSheet("")
        self.slogan.setText("")
        self.slogan.setPixmap(QtGui.QPixmap(".\\ui\\uiFiles\\../../assets/Drive_Freedom_Rent_Easy.png"))
        self.slogan.setScaledContents(False)
        self.slogan.setObjectName("slogan")
        self.horizontalLayout_4.addWidget(self.slogan)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(-1, 12, 17, 12)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.nameLabel = QtWidgets.QLabel(parent=self.titleWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono Medium")
        font.setPointSize(15)
        self.nameLabel.setFont(font)
        self.nameLabel.setStyleSheet("color: white;")
        self.nameLabel.setObjectName("nameLabel")
        self.verticalLayout_8.addWidget(self.nameLabel, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.prevligedLabel = QtWidgets.QLabel(parent=self.titleWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono Light")
        font.setPointSize(10)
        self.prevligedLabel.setFont(font)
        self.prevligedLabel.setStyleSheet("color: white;")
        self.prevligedLabel.setObjectName("prevligedLabel")
        self.verticalLayout_8.addWidget(self.prevligedLabel, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        self.profileIcon = QtWidgets.QLabel(parent=self.titleWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profileIcon.sizePolicy().hasHeightForWidth())
        self.profileIcon.setSizePolicy(sizePolicy)
        self.profileIcon.setMinimumSize(QtCore.QSize(48, 0))
        self.profileIcon.setMaximumSize(QtCore.QSize(48, 16777215))
        self.profileIcon.setStyleSheet("")
        self.profileIcon.setText("")
        self.profileIcon.setPixmap(QtGui.QPixmap(".\\ui\\uiFiles\\../../assets/icons/profile_1.png"))
        self.profileIcon.setObjectName("profileIcon")
        self.horizontalLayout_4.addWidget(self.profileIcon)
        self.verticalLayout.addWidget(self.titleWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.filterWidget = QtWidgets.QWidget(parent=car_selection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterWidget.sizePolicy().hasHeightForWidth())
        self.filterWidget.setSizePolicy(sizePolicy)
        self.filterWidget.setMinimumSize(QtCore.QSize(300, 0))
        self.filterWidget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.filterWidget.setStyleSheet("#filterWidget {\n"
"    background-color: #1E1E1E;\n"
"}")
        self.filterWidget.setObjectName("filterWidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.filterWidget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.priceFilterWidget = QtWidgets.QWidget(parent=self.filterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.priceFilterWidget.sizePolicy().hasHeightForWidth())
        self.priceFilterWidget.setSizePolicy(sizePolicy)
        self.priceFilterWidget.setMinimumSize(QtCore.QSize(0, 100))
        self.priceFilterWidget.setMaximumSize(QtCore.QSize(16777215, 120))
        self.priceFilterWidget.setStyleSheet("QLineEdit {\n"
"    border-radius : 4px;\n"
"    border: None;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: white;\n"
"}\n"
"\n"
" #priceFilterWidget {\n"
"    border-bottom: 2px solid white;\n"
"    border-top: 2px solid white;\n"
"}\n"
"\n"
"")
        self.priceFilterWidget.setObjectName("priceFilterWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.priceFilterWidget)
        self.verticalLayout_4.setContentsMargins(15, 20, 15, 10)
        self.verticalLayout_4.setSpacing(12)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.priceLabel = QtWidgets.QLabel(parent=self.priceFilterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.priceLabel.sizePolicy().hasHeightForWidth())
        self.priceLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono Medium")
        font.setPointSize(18)
        self.priceLabel.setFont(font)
        self.priceLabel.setStyleSheet("")
        self.priceLabel.setObjectName("priceLabel")
        self.verticalLayout_4.addWidget(self.priceLabel)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(15)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.maxPriceTextF = QtWidgets.QLineEdit(parent=self.priceFilterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxPriceTextF.sizePolicy().hasHeightForWidth())
        self.maxPriceTextF.setSizePolicy(sizePolicy)
        self.maxPriceTextF.setMinimumSize(QtCore.QSize(50, 35))
        self.maxPriceTextF.setMaximumSize(QtCore.QSize(50, 35))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(9)
        self.maxPriceTextF.setFont(font)
        self.maxPriceTextF.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.maxPriceTextF.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.maxPriceTextF.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.maxPriceTextF.setText("")
        self.maxPriceTextF.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.maxPriceTextF.setObjectName("maxPriceTextF")
        self.horizontalLayout_3.addWidget(self.maxPriceTextF)
        self.minPriceTextF = QtWidgets.QLineEdit(parent=self.priceFilterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minPriceTextF.sizePolicy().hasHeightForWidth())
        self.minPriceTextF.setSizePolicy(sizePolicy)
        self.minPriceTextF.setMinimumSize(QtCore.QSize(50, 35))
        self.minPriceTextF.setMaximumSize(QtCore.QSize(50, 35))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(9)
        self.minPriceTextF.setFont(font)
        self.minPriceTextF.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.minPriceTextF.setText("")
        self.minPriceTextF.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.minPriceTextF.setObjectName("minPriceTextF")
        self.horizontalLayout_3.addWidget(self.minPriceTextF)
        spacerItem = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_7.addWidget(self.priceFilterWidget)
        self.yearFilterWidget = QtWidgets.QWidget(parent=self.filterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yearFilterWidget.sizePolicy().hasHeightForWidth())
        self.yearFilterWidget.setSizePolicy(sizePolicy)
        self.yearFilterWidget.setMinimumSize(QtCore.QSize(0, 100))
        self.yearFilterWidget.setMaximumSize(QtCore.QSize(16777215, 120))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.yearFilterWidget.setFont(font)
        self.yearFilterWidget.setStyleSheet("QLineEdit {\n"
"    border-radius : 4px;\n"
"    border: None;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: white;\n"
"}\n"
"\n"
" #yearFilterWidget {\n"
"    border-bottom: 2px solid white;\n"
"}\n"
"\n"
"")
        self.yearFilterWidget.setObjectName("yearFilterWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.yearFilterWidget)
        self.verticalLayout_3.setContentsMargins(15, 10, 15, 10)
        self.verticalLayout_3.setSpacing(12)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.yearLabel = QtWidgets.QLabel(parent=self.yearFilterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yearLabel.sizePolicy().hasHeightForWidth())
        self.yearLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono Medium")
        font.setPointSize(18)
        self.yearLabel.setFont(font)
        self.yearLabel.setObjectName("yearLabel")
        self.verticalLayout_3.addWidget(self.yearLabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(15)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.maxYearTextF = QtWidgets.QLineEdit(parent=self.yearFilterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxYearTextF.sizePolicy().hasHeightForWidth())
        self.maxYearTextF.setSizePolicy(sizePolicy)
        self.maxYearTextF.setMinimumSize(QtCore.QSize(50, 35))
        self.maxYearTextF.setMaximumSize(QtCore.QSize(50, 35))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(9)
        self.maxYearTextF.setFont(font)
        self.maxYearTextF.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.maxYearTextF.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.maxYearTextF.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.maxYearTextF.setText("")
        self.maxYearTextF.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.maxYearTextF.setObjectName("maxYearTextF")
        self.horizontalLayout_2.addWidget(self.maxYearTextF)
        self.minYearTextF = QtWidgets.QLineEdit(parent=self.yearFilterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minYearTextF.sizePolicy().hasHeightForWidth())
        self.minYearTextF.setSizePolicy(sizePolicy)
        self.minYearTextF.setMinimumSize(QtCore.QSize(50, 35))
        self.minYearTextF.setMaximumSize(QtCore.QSize(50, 35))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(9)
        self.minYearTextF.setFont(font)
        self.minYearTextF.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.minYearTextF.setText("")
        self.minYearTextF.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.minYearTextF.setObjectName("minYearTextF")
        self.horizontalLayout_2.addWidget(self.minYearTextF)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_7.addWidget(self.yearFilterWidget)
        self.gearTypeWidget = QtWidgets.QWidget(parent=self.filterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gearTypeWidget.sizePolicy().hasHeightForWidth())
        self.gearTypeWidget.setSizePolicy(sizePolicy)
        self.gearTypeWidget.setMinimumSize(QtCore.QSize(0, 95))
        self.gearTypeWidget.setMaximumSize(QtCore.QSize(16777215, 95))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.gearTypeWidget.setFont(font)
        self.gearTypeWidget.setStyleSheet("QWidget {\n"
"    color : white;\n"
"}\n"
"\n"
"QCheckBox::indicator { /* Kutu kısmını temsil eder */\n"
"    border: none;  /* Kenarlığı kaldır */\n"
"    background-color: white;  /* İç rengi beyaz yap */\n"
"    border-radius : 3px;\n"
"}\n"
"\n"
"#gearTypeWidget {\n"
"    border-bottom: 2px solid white;\n"
"}")
        self.gearTypeWidget.setObjectName("gearTypeWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.gearTypeWidget)
        self.verticalLayout_5.setContentsMargins(15, 10, 15, 10)
        self.verticalLayout_5.setSpacing(12)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gearTypeLabel = QtWidgets.QLabel(parent=self.gearTypeWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gearTypeLabel.sizePolicy().hasHeightForWidth())
        self.gearTypeLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono Medium")
        font.setPointSize(18)
        self.gearTypeLabel.setFont(font)
        self.gearTypeLabel.setObjectName("gearTypeLabel")
        self.verticalLayout_5.addWidget(self.gearTypeLabel, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.automatic = QtWidgets.QCheckBox(parent=self.gearTypeWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono Light")
        font.setPointSize(10)
        self.automatic.setFont(font)
        self.automatic.setObjectName("automatic")
        self.horizontalLayout_5.addWidget(self.automatic)
        self.manual = QtWidgets.QCheckBox(parent=self.gearTypeWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono Light")
        font.setPointSize(10)
        self.manual.setFont(font)
        self.manual.setObjectName("manual")
        self.horizontalLayout_5.addWidget(self.manual)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.verticalLayout_7.addWidget(self.gearTypeWidget)
        self.fuelTypeWidget = QtWidgets.QWidget(parent=self.filterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fuelTypeWidget.sizePolicy().hasHeightForWidth())
        self.fuelTypeWidget.setSizePolicy(sizePolicy)
        self.fuelTypeWidget.setMinimumSize(QtCore.QSize(0, 100))
        self.fuelTypeWidget.setMaximumSize(QtCore.QSize(16777215, 120))
        self.fuelTypeWidget.setBaseSize(QtCore.QSize(0, 0))
        self.fuelTypeWidget.setStyleSheet("QWidget {\n"
"    color : white;\n"
"}\n"
"\n"
"QCheckBox::indicator { /* Kutu kısmını temsil eder */\n"
"    border: none;  /* Kenarlığı kaldır */\n"
"    background-color: white;  /* İç rengi beyaz yap */\n"
"    border-radius : 3px;\n"
"}\n"
"\n"
"#fuelTypeWidget {\n"
"    border-bottom: 2px solid white;\n"
"}")
        self.fuelTypeWidget.setObjectName("fuelTypeWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.fuelTypeWidget)
        self.verticalLayout_6.setContentsMargins(15, 10, 15, 10)
        self.verticalLayout_6.setSpacing(12)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.fuelTypeLabel = QtWidgets.QLabel(parent=self.fuelTypeWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fuelTypeLabel.sizePolicy().hasHeightForWidth())
        self.fuelTypeLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono Medium")
        font.setPointSize(18)
        self.fuelTypeLabel.setFont(font)
        self.fuelTypeLabel.setObjectName("fuelTypeLabel")
        self.verticalLayout_6.addWidget(self.fuelTypeLabel, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.gasoline = QtWidgets.QCheckBox(parent=self.fuelTypeWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono Light")
        font.setPointSize(10)
        self.gasoline.setFont(font)
        self.gasoline.setObjectName("gasoline")
        self.horizontalLayout_6.addWidget(self.gasoline)
        self.diesel = QtWidgets.QCheckBox(parent=self.fuelTypeWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono Light")
        font.setPointSize(10)
        self.diesel.setFont(font)
        self.diesel.setStyleSheet("")
        self.diesel.setObjectName("diesel")
        self.horizontalLayout_6.addWidget(self.diesel)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.verticalLayout_7.addWidget(self.fuelTypeWidget, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.statusWidget = QtWidgets.QWidget(parent=self.filterWidget)
        self.statusWidget.setStyleSheet("QWidget {\n"
"    color : white;\n"
"}\n"
"\n"
"QCheckBox::indicator { /* Kutu kısmını temsil eder */\n"
"    border: none;  /* Kenarlığı kaldır */\n"
"    background-color: white;  /* İç rengi beyaz yap */\n"
"    border-radius : 3px;\n"
"}\n"
"\n"
"#statusWidget {\n"
"    border-bottom: 2px solid white;\n"
"}")
        self.statusWidget.setObjectName("statusWidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.statusWidget)
        self.horizontalLayout_7.setContentsMargins(15, 10, 15, 10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.fuelTypeLabel_2 = QtWidgets.QLabel(parent=self.statusWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fuelTypeLabel_2.sizePolicy().hasHeightForWidth())
        self.fuelTypeLabel_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono Medium")
        font.setPointSize(18)
        self.fuelTypeLabel_2.setFont(font)
        self.fuelTypeLabel_2.setObjectName("fuelTypeLabel_2")
        self.horizontalLayout_7.addWidget(self.fuelTypeLabel_2)
        self.checkBox = QtWidgets.QCheckBox(parent=self.statusWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono Light")
        font.setPointSize(10)
        font.setKerning(True)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_7.addWidget(self.checkBox)
        self.verticalLayout_7.addWidget(self.statusWidget)
        self.searchLayout = QtWidgets.QVBoxLayout()
        self.searchLayout.setContentsMargins(15, 20, 15, 20)
        self.searchLayout.setSpacing(10)
        self.searchLayout.setObjectName("searchLayout")
        self.searchTextF = QtWidgets.QLineEdit(parent=self.filterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchTextF.sizePolicy().hasHeightForWidth())
        self.searchTextF.setSizePolicy(sizePolicy)
        self.searchTextF.setMinimumSize(QtCore.QSize(0, 50))
        self.searchTextF.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono Medium")
        font.setPointSize(11)
        self.searchTextF.setFont(font)
        self.searchTextF.setStyleSheet("QLineEdit {\n"
"    padding-left : 10px;\n"
"    border: 2px solid #BFBFBF;\n"
"    border-radius : 5px;\n"
"    background-color: transparent;\n"
"    color : #BFBFBF;\n"
"}\n"
"\n"
"")
        self.searchTextF.setClearButtonEnabled(False)
        self.searchTextF.setObjectName("searchTextF")
        self.searchLayout.addWidget(self.searchTextF)
        self.applyBtn = QtWidgets.QPushButton(parent=self.filterWidget)
        self.applyBtn.setMinimumSize(QtCore.QSize(0, 48))
        self.applyBtn.setMaximumSize(QtCore.QSize(16777215, 48))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono Medium")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.applyBtn.setFont(font)
        self.applyBtn.setStyleSheet("QPushButton {\n"
"    background-color: #1B47E5;\n"
"    color : white;\n"
"    border-radius: 4px;\n"
"    font: 57 11pt \"Roboto Mono Medium\";\n"
"}")
        self.applyBtn.setObjectName("applyBtn")
        self.searchLayout.addWidget(self.applyBtn)
        self.verticalLayout_7.addLayout(self.searchLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_7.addItem(spacerItem2)
        self.horizontalLayout.addWidget(self.filterWidget)
        self.scrollArea = QtWidgets.QScrollArea(parent=car_selection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.scrollArea.setFont(font)
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.carWidget = QtWidgets.QWidget()
        self.carWidget.setGeometry(QtCore.QRect(0, 0, 767, 697))
        self.carWidget.setStyleSheet("")
        self.carWidget.setObjectName("carWidget")
        self.carWidgetLayout = QtWidgets.QHBoxLayout(self.carWidget)
        self.carWidgetLayout.setContentsMargins(0, 0, 0, 0)
        self.carWidgetLayout.setSpacing(0)
        self.carWidgetLayout.setObjectName("carWidgetLayout")
        self.scrollArea.setWidget(self.carWidget)
        self.horizontalLayout.addWidget(self.scrollArea)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(car_selection)
        QtCore.QMetaObject.connectSlotsByName(car_selection)

    def retranslateUi(self, car_selection):
        _translate = QtCore.QCoreApplication.translate
        car_selection.setWindowTitle(_translate("car_selection", "Form"))
        self.nameLabel.setText(_translate("car_selection", "John Doe"))
        self.prevligedLabel.setText(_translate("car_selection", "User"))
        self.priceLabel.setText(_translate("car_selection", "Price"))
        self.maxPriceTextF.setPlaceholderText(_translate("car_selection", "min"))
        self.minPriceTextF.setPlaceholderText(_translate("car_selection", "max"))
        self.yearLabel.setText(_translate("car_selection", "Year"))
        self.maxYearTextF.setPlaceholderText(_translate("car_selection", "min"))
        self.minYearTextF.setPlaceholderText(_translate("car_selection", "max"))
        self.gearTypeLabel.setText(_translate("car_selection", "Gear"))
        self.automatic.setText(_translate("car_selection", "Automatic"))
        self.manual.setText(_translate("car_selection", "Manual"))
        self.fuelTypeLabel.setText(_translate("car_selection", "Fuel Types"))
        self.gasoline.setText(_translate("car_selection", "Gasoline"))
        self.diesel.setText(_translate("car_selection", "Diesel"))
        self.fuelTypeLabel_2.setText(_translate("car_selection", "Status"))
        self.checkBox.setText(_translate("car_selection", "Available"))
        self.searchTextF.setPlaceholderText(_translate("car_selection", "Search"))
        self.applyBtn.setText(_translate("car_selection", "Apply"))
