# Form implementation generated from reading ui file '.\ui\uiFiles\loginWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(800, 600)
        Login.setStyleSheet("#Login {\n"
"    border-image: url(:/bg/assets/tireTrackBg.jpg);\n"
"}\n"
"\n"
"QLineEdit {\n"
"    padding-left : 10px;\n"
"    border: None;\n"
"    border-radius : 4px;\n"
"    background-color: rgb(37, 42, 52);\n"
"    color : white;\n"
"}\n"
"\n"
"")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Login)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.loginLabel = QtWidgets.QLabel(parent=Login)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loginLabel.sizePolicy().hasHeightForWidth())
        self.loginLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono Medium")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.loginLabel.setFont(font)
        self.loginLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.loginLabel.setObjectName("loginLabel")
        self.verticalLayout_2.addWidget(self.loginLabel)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(23)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.usernameTf = QtWidgets.QLineEdit(parent=Login)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.usernameTf.sizePolicy().hasHeightForWidth())
        self.usernameTf.setSizePolicy(sizePolicy)
        self.usernameTf.setMinimumSize(QtCore.QSize(400, 45))
        self.usernameTf.setMaximumSize(QtCore.QSize(500, 45))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.usernameTf.setFont(font)
        self.usernameTf.setObjectName("usernameTf")
        self.verticalLayout.addWidget(self.usernameTf, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.passwordTf = QtWidgets.QLineEdit(parent=Login)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passwordTf.sizePolicy().hasHeightForWidth())
        self.passwordTf.setSizePolicy(sizePolicy)
        self.passwordTf.setMinimumSize(QtCore.QSize(400, 45))
        self.passwordTf.setMaximumSize(QtCore.QSize(500, 45))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.passwordTf.setFont(font)
        self.passwordTf.setObjectName("passwordTf")
        self.verticalLayout.addWidget(self.passwordTf, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.loginBtn = QtWidgets.QPushButton(parent=Login)
        self.loginBtn.setMinimumSize(QtCore.QSize(400, 40))
        self.loginBtn.setMaximumSize(QtCore.QSize(500, 40))
        self.loginBtn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 46, 99);\n"
"    color : white;\n"
"    border-radius: 4px;\n"
"    font: 57 11pt \"Roboto Mono Medium\";\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color: rgb(255, 46, 168);\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color: rgba(255, 46, 168, 140);\n"
"}")
        self.loginBtn.setObjectName("loginBtn")
        self.verticalLayout.addWidget(self.loginBtn, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.label_2 = QtWidgets.QLabel(parent=Login)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.registerBtn = QtWidgets.QLabel(parent=Login)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.registerBtn.sizePolicy().hasHeightForWidth())
        self.registerBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setBold(True)
        font.setWeight(75)
        self.registerBtn.setFont(font)
        self.registerBtn.setObjectName("registerBtn")
        self.horizontalLayout.addWidget(self.registerBtn, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Form"))
        self.loginLabel.setText(_translate("Login", "Login"))
        self.usernameTf.setPlaceholderText(_translate("Login", "Username or Mail"))
        self.passwordTf.setPlaceholderText(_translate("Login", "Password"))
        self.loginBtn.setText(_translate("Login", "Login"))
        self.label_2.setText(_translate("Login", "Don\'t have an account?"))
        self.registerBtn.setText(_translate("Login", "Register"))
