# Form implementation generated from reading ui file '.\ui\uiFiles\registerWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Register(object):
    def setupUi(self, Register):
        Register.setObjectName("Register")
        Register.resize(800, 600)
        Register.setStyleSheet("QLineEdit {\n"
"    padding-left : 10px;\n"
"    border: None;\n"
"    border-radius : 4px;\n"
"    background-color: rgb(37, 42, 52);\n"
"    color : white;\n"
"}\n"
"\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Register)
        self.verticalLayout.setSpacing(40)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.registerLabel = QtWidgets.QLabel(parent=Register)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.registerLabel.sizePolicy().hasHeightForWidth())
        self.registerLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(35)
        self.registerLabel.setFont(font)
        self.registerLabel.setObjectName("registerLabel")
        self.verticalLayout.addWidget(self.registerLabel, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(5)
        self.gridLayout.setVerticalSpacing(35)
        self.gridLayout.setObjectName("gridLayout")
        self.idTf = QtWidgets.QLineEdit(parent=Register)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.idTf.sizePolicy().hasHeightForWidth())
        self.idTf.setSizePolicy(sizePolicy)
        self.idTf.setMinimumSize(QtCore.QSize(350, 55))
        self.idTf.setMaximumSize(QtCore.QSize(350, 55))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.idTf.setFont(font)
        self.idTf.setObjectName("idTf")
        self.gridLayout.addWidget(self.idTf, 1, 0, 1, 1)
        self.birthDateTf = QtWidgets.QLineEdit(parent=Register)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.birthDateTf.sizePolicy().hasHeightForWidth())
        self.birthDateTf.setSizePolicy(sizePolicy)
        self.birthDateTf.setMinimumSize(QtCore.QSize(350, 55))
        self.birthDateTf.setMaximumSize(QtCore.QSize(350, 55))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.birthDateTf.setFont(font)
        self.birthDateTf.setObjectName("birthDateTf")
        self.gridLayout.addWidget(self.birthDateTf, 3, 0, 1, 1)
        self.passwordTf = QtWidgets.QLineEdit(parent=Register)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passwordTf.sizePolicy().hasHeightForWidth())
        self.passwordTf.setSizePolicy(sizePolicy)
        self.passwordTf.setMinimumSize(QtCore.QSize(350, 55))
        self.passwordTf.setMaximumSize(QtCore.QSize(350, 55))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.passwordTf.setFont(font)
        self.passwordTf.setText("")
        self.passwordTf.setObjectName("passwordTf")
        self.gridLayout.addWidget(self.passwordTf, 0, 1, 1, 1)
        self.passwordAgainTf = QtWidgets.QLineEdit(parent=Register)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passwordAgainTf.sizePolicy().hasHeightForWidth())
        self.passwordAgainTf.setSizePolicy(sizePolicy)
        self.passwordAgainTf.setMinimumSize(QtCore.QSize(350, 55))
        self.passwordAgainTf.setMaximumSize(QtCore.QSize(350, 55))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.passwordAgainTf.setFont(font)
        self.passwordAgainTf.setObjectName("passwordAgainTf")
        self.gridLayout.addWidget(self.passwordAgainTf, 1, 1, 1, 1)
        self.usernameTf = QtWidgets.QLineEdit(parent=Register)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.usernameTf.sizePolicy().hasHeightForWidth())
        self.usernameTf.setSizePolicy(sizePolicy)
        self.usernameTf.setMinimumSize(QtCore.QSize(350, 55))
        self.usernameTf.setMaximumSize(QtCore.QSize(350, 55))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.usernameTf.setFont(font)
        self.usernameTf.setObjectName("usernameTf")
        self.gridLayout.addWidget(self.usernameTf, 0, 0, 1, 1)
        self.driverLicenceTf = QtWidgets.QPushButton(parent=Register)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.driverLicenceTf.sizePolicy().hasHeightForWidth())
        self.driverLicenceTf.setSizePolicy(sizePolicy)
        self.driverLicenceTf.setMinimumSize(QtCore.QSize(350, 55))
        self.driverLicenceTf.setMaximumSize(QtCore.QSize(350, 55))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.driverLicenceTf.setFont(font)
        self.driverLicenceTf.setStyleSheet("QPushButton  {\n"
"    background-color: rgb(8, 217, 214);\n"
"    color : white;\n"
"    border-radius: 4px;\n"
"}")
        self.driverLicenceTf.setObjectName("driverLicenceTf")
        self.gridLayout.addWidget(self.driverLicenceTf, 3, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.registerBtn = QtWidgets.QPushButton(parent=Register)
        self.registerBtn.setMinimumSize(QtCore.QSize(400, 40))
        self.registerBtn.setMaximumSize(QtCore.QSize(500, 40))
        self.registerBtn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 46, 99);\n"
"    color : white;\n"
"    border-radius: 4px;\n"
"    font: 57 11pt \"Roboto Mono Medium\";\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color: rgb(255, 46, 168);\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color: rgba(255, 46, 168, 140);\n"
"}")
        self.registerBtn.setObjectName("registerBtn")
        self.verticalLayout.addWidget(self.registerBtn, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(Register)
        QtCore.QMetaObject.connectSlotsByName(Register)

    def retranslateUi(self, Register):
        _translate = QtCore.QCoreApplication.translate
        Register.setWindowTitle(_translate("Register", "Form"))
        self.registerLabel.setText(_translate("Register", "Register"))
        self.idTf.setPlaceholderText(_translate("Register", "ID Number"))
        self.birthDateTf.setPlaceholderText(_translate("Register", "Birth Date"))
        self.passwordTf.setPlaceholderText(_translate("Register", "Password"))
        self.passwordAgainTf.setPlaceholderText(_translate("Register", "Password Again"))
        self.usernameTf.setPlaceholderText(_translate("Register", "Username or Mail"))
        self.driverLicenceTf.setText(_translate("Register", "Upload Your Driver Licence"))
        self.registerBtn.setText(_translate("Register", "Register"))
