# Form implementation generated from reading ui file '.\ui\uiFiles\vehicleCard.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_vehicle_card(object):
    def setupUi(self, vehicle_card):
        vehicle_card.setObjectName("vehicle_card")
        vehicle_card.resize(300, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(vehicle_card.sizePolicy().hasHeightForWidth())
        vehicle_card.setSizePolicy(sizePolicy)
        vehicle_card.setMinimumSize(QtCore.QSize(300, 300))
        vehicle_card.setMaximumSize(QtCore.QSize(300, 300))
        vehicle_card.setStyleSheet("border-radius:4px;")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(vehicle_card)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(parent=vehicle_card)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(300, 300))
        self.frame.setMaximumSize(QtCore.QSize(300, 300))
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: #383838;\n"
"    color: #F0F0F0;\n"
"    border-radius: 9px;\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.brand = QtWidgets.QLabel(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brand.sizePolicy().hasHeightForWidth())
        self.brand.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono Medium")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.brand.setFont(font)
        self.brand.setObjectName("brand")
        self.verticalLayout.addWidget(self.brand)
        self.features = QtWidgets.QLabel(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.features.sizePolicy().hasHeightForWidth())
        self.features.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono Light")
        font.setPointSize(9)
        self.features.setFont(font)
        self.features.setObjectName("features")
        self.verticalLayout.addWidget(self.features)
        self.carImage = QtWidgets.QLabel(parent=self.frame)
        self.carImage.setText("")
        self.carImage.setPixmap(QtGui.QPixmap(".\\ui\\uiFiles\\../../assets/cars/clio.webp"))
        self.carImage.setScaledContents(True)
        self.carImage.setObjectName("carImage")
        self.verticalLayout.addWidget(self.carImage)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.price = QtWidgets.QLabel(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.price.sizePolicy().hasHeightForWidth())
        self.price.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono Medium")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.price.setFont(font)
        self.price.setObjectName("price")
        self.horizontalLayout.addWidget(self.price)
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.frame)

        self.retranslateUi(vehicle_card)
        QtCore.QMetaObject.connectSlotsByName(vehicle_card)

    def retranslateUi(self, vehicle_card):
        _translate = QtCore.QCoreApplication.translate
        vehicle_card.setWindowTitle(_translate("vehicle_card", "Form"))
        self.brand.setText(_translate("vehicle_card", "Renualt Clio"))
        self.features.setText(_translate("vehicle_card", "Otomatik | Dizel | 2024"))
        self.price.setText(_translate("vehicle_card", "$10"))
        self.label_3.setText(_translate("vehicle_card", "| Daily"))
